In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


%matplotlib inline

In [4]:
flight_train = pd.read_csv('flight_data_train.csv')
flight_train.sample(5)

,Day_Id,Spot1 maxDistance,Spot1 totalDistance,Spot1 totalFlights,Spot2 maxDistance,Spot2 totalDistance,Spot2 totalFlights,Spot3 maxDistance,Spot3 totalDistance,Spot3 totalFlights,...,Spot285 totalFlights,Spot286 maxDistance,Spot286 totalDistance,Spot286 totalFlights,Spot287 maxDistance,Spot287 totalDistance,Spot287 totalFlights,Spot288 maxDistance,Spot288 totalDistance,Spot288 totalFlights
753,801,83.09,614.95,9,0.0,0.0,0,0.0,0.0,0,...,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0
862,915,0.00,0.00,0,0.0,0.0,0,0.0,0.0,0,...,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0
1450,1542,0.00,0.00,0,0.0,0.0,0,0.0,0.0,0,...,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0
740,786,5.42,5.42,1,0.0,0.0,0,0.0,0.0,0,...,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0
1001,1067,0.00,0.00,0,0.0,0.0,0,0.0,0.0,0,...,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0

In [5]:
weather_train = pd.read_csv('weather_data_train.csv')
weather_train.sample(5)

,Day_Id,Station1 Dew Point Height1,Station1 Dew Point Height2,Station1 Dew Point Height3,Station1 Dew Point Height4,Station1 Dew Point Height5,Station1 Dew Point Height6,Station1 Dew Point Height7,Station1 Dew Point Height8,Station1 Dew Point Height9,...,Station5 Wind Speed Height36,Station5 Wind Speed Height37,Station5 Wind Speed Height38,Station5 Wind Speed Height39,Station5 Wind Speed Height40,Station5 Wind Speed Height41,Station5 Wind Speed Height42,Station5 Wind Speed Height43,Station5 Wind Speed Height44,Station5 Wind Speed Height45
1856,1985,12.541935,12.265438,11.989262,11.720805,11.584786,11.557123,11.529461,11.501798,11.474136,...,25.215881,25.339950,25.464020,25.588089,25.712159,25.836228,25.960298,26.084367,26.208437,26.332506
2082,2222,8.675410,9.003279,9.331148,8.573234,8.275836,7.978439,7.681041,7.383643,7.086245,...,28.982924,29.496980,30.014668,30.532355,31.050043,31.567731,32.085418,32.603106,33.120794,33.638481
2059,2198,15.678261,16.570000,17.494262,18.483333,14.856716,7.012821,5.137652,5.056680,4.934066,...,23.804576,23.899905,23.995234,24.090562,24.185891,24.281220,24.376549,24.471878,24.567207,24.662536
2105,2248,13.013699,12.882736,12.752443,12.622150,12.417331,12.197249,11.977166,11.757084,11.537001,...,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000
579,614,16.232107,15.830769,15.429431,15.028094,14.296639,13.540336,14.331429,16.388571,15.128358,...,37.348548,39.008299,40.668050,41.941176,43.157895,44.736842,46.315789,47.894737,49.473684,51.052632

In [7]:
weather_test = pd.read_csv('weather_data_test.csv')
weather_test.sample(5)

,Day_Id,Station1 Dew Point Height1,Station1 Dew Point Height2,Station1 Dew Point Height3,Station1 Dew Point Height4,Station1 Dew Point Height5,Station1 Dew Point Height6,Station1 Dew Point Height7,Station1 Dew Point Height8,Station1 Dew Point Height9,...,Station5 Wind Speed Height36,Station5 Wind Speed Height37,Station5 Wind Speed Height38,Station5 Wind Speed Height39,Station5 Wind Speed Height40,Station5 Wind Speed Height41,Station5 Wind Speed Height42,Station5 Wind Speed Height43,Station5 Wind Speed Height44,Station5 Wind Speed Height45
29,697,3.628936,2.480000,1.371984,0.905058,0.438132,-0.026359,-0.488315,-0.950272,-1.412228,...,8.267946,8.196873,8.125800,8.054726,8.000000,9.154762,10.242678,11.079498,11.916318,11.108911
8,230,9.673846,10.904615,12.135385,13.366154,14.339896,15.272539,13.800000,6.252174,6.469565,...,28.971429,29.800000,30.633333,31.466667,32.300000,33.116788,33.846715,34.576642,35.306569,36.036496
98,2307,5.302041,4.485714,3.669388,3.400000,3.312849,3.201117,3.136129,3.062232,2.976395,...,54.215909,54.594697,54.973485,55.902913,57.140794,57.501805,57.862816,58.475877,59.243421,60.010965
45,1033,7.635200,6.460606,5.652525,5.260392,5.397647,5.534902,5.672157,5.809412,5.950746,...,36.066667,38.288889,40.511111,42.733333,44.955556,47.177778,49.400000,51.622222,53.853933,56.101124
36,894,-1.152381,-3.057143,-4.961905,-6.866667,-7.941176,-7.549020,-9.340136,-12.128463,-12.984887,...,30.093586,30.159031,30.224476,30.289921,30.355366,30.420812,30.486257,30.551702,30.617147,30.682592